# Generated by Django 3.2.9 on 2021-11-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_algorithm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrycode', models.CharField(max_length=3, verbose_name='countrycode')),
                ('country', models.CharField(max_length=30, verbose_name='country')),
                ('year', models.IntegerField(verbose_name='year')),
                ('pop', models.FloatField(verbose_name='pop')),
                ('rgdpna', models.FloatField(verbose_name='rgdpna')),
                ('delta', models.FloatField(verbose_name='delta')),
                ('xr', models.FloatField(verbose_name='xr')),
                ('csh_c', models.FloatField(verbose_name='csh_c')),
                ('csh_i', models.FloatField(verbose_name='csh_i')),
                ('csh_g', models.FloatField(verbose_name='csh_g')),
                ('csh_x', models.FloatField(verbose_name='csh_x')),
                ('csh_m', models.FloatField(verbose_name='csh_m')),
                ('csh_r', models.FloatField(verbose_name='csh_r')),
                ('rgdpna_per_cap', models.FloatField(verbose_name='rgdpna_per_cap')),
                ('emp_percent', models.FloatField(verbose_name='emp_percent')),
                ('co2_emission', models.FloatField(verbose_name='co2_emission')),
                ('employment_agro', models.FloatField(verbose_name='employment_agro')),
                ('employment_industry', models.FloatField(verbose_name='employment_industry')),
                ('employment_services', models.FloatField(verbose_name='employment_services')),
                ('export', models.FloatField(verbose_name='export')),
                ('import_value', models.FloatField(verbose_name='import_value')),
                ('inflation', models.FloatField(verbose_name='inflation')),
                ('net_migration', models.FloatField(verbose_name='net_migration')),
                ('population_15_64', models.FloatField(verbose_name='population_15_64')),
                ('population_above_65', models.FloatField(verbose_name='population_above_65')),
                ('population_under_14', models.FloatField(verbose_name='population_under_14')),
                ('unemployment', models.FloatField(verbose_name='unemployment')),
                ('urban_population', models.FloatField(verbose_name='urban_population')),
                ('hdi', models.FloatField(verbose_name='hdi')),
            ],
        ),
    ]
