# Generated by Django 3.2.9 on 2021-12-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=50, verbose_name='algorithm')),
                ('n_clusters', models.IntegerField(verbose_name='n_clusters')),
                ('silhouette', models.FloatField(verbose_name='silhouette')),
                ('chscore', models.FloatField(verbose_name='chscore')),
                ('dunnindex', models.FloatField(verbose_name='dunnindex')),
            ],
        ),
    ]
