# Generated by Django 3.2.9 on 2021-12-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_metricsvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsvalues',
            name='chscore',
            field=models.FloatField(blank=True, null=True, verbose_name='chscore'),
        ),
        migrations.AlterField(
            model_name='metricsvalues',
            name='dunnindex',
            field=models.FloatField(blank=True, null=True, verbose_name='dunnindex'),
        ),
        migrations.AlterField(
            model_name='metricsvalues',
            name='silhouette',
            field=models.FloatField(blank=True, null=True, verbose_name='silhouette'),
        ),
    ]
