# Generated by Django 3.2.9 on 2022-01-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_dataoriginal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Algorithm',
        ),
    ]
